---
- name: Check Uptime for Windows Server and Send Email
  hosts: win
  gather_facts: no

  tasks:
    - name: Get system information
      win_command: systeminfo
      register: system_info

    - name: Extract uptime
      set_fact:
        uptime_line: "{{ system_info.stdout_lines | select('match', '^\\s*System Boot Time') | list | first }}"

    - name: Create CSV content
      set_fact:
        csv_content: |
          Server,Uptime
          {{ ansible_host }},{{ uptime_line | regex_replace('^\\s*System Boot Time:\\s*','') }}

    - name: Save CSV to file
      copy:
        content: "{{ csv_content }}"
        dest: "/tmp/server_uptime.csv"
      delegate_to: localhost

    - name: Send email with CSV attachment
      mail:
        to: jvnkumarofficial1993@gmail.com
        subject: "Server Uptime Report"
        body: "Please find the attached CSV file with server uptime information."
        attach: "/tmp/server_uptime.csv"
      delegate_to: localhost


